---

- name: Install nodejs
  apt: pkg=nodejs state=present

- name: Install npm
  apt: pkg=npm state=present

- name: Symlink nodejs for npm
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Download ghost
  get_url: dest={{ zip_file }} url={{ download_url }}

- name: Create ghost dir
  file: path={{ ghost_dir }} state=directory

- name: Extract ghost
  unarchive: src={{ zip_file }} dest={{ ghost_dir }} copy=no creates="{{ ghost_dir }}/package.json"

- name: Install ghost
  npm: path={{ ghost_dir }} production=true executable=/usr/bin/npm

- name: Install readdirp
  npm: name=readdirp executable=/usr/bin/npm global=yes

- name: Install handlebars
  npm: name=readdirp executable=/usr/bin/npm global=yes

- name: Configure ghost
  template: src=config.js.j2 dest="{{ ghost_dir }}/config.js"
  notify: restart ghost

- name: Configure init script
  template: src=ghost.j2 dest=/etc/init.d/ghost mode=755

# - name: Clone ghost content git repo
#   git: repo={{ content_repo }} dest="{{ content_dir }}" update=yes accept_hostkey=yes

- name: Create ghost-content dir
  file: path={{ content_dir }} state=directory

- name: Ensure ghost service enabled and running
  service: name=ghost state=started enabled=yes
