---

- name: Build jekyll site locally
  sudo: false
  local_action: command jekyll build chdir={{ jekyll_src }}

- name: Sync jekyll site
  synchronize: src={{ jekyll_dest }} dest={{ www_root }} checksum=yes delete=yes
